# File: docker-compose.yml

# Note: version is obsolete and will be ignored, as mentioned in Docker warning

services:
  postgres:
    image: joseabad985/wildfly-angular-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wildfly:
    image: joseabad985/wildfly-angular-backend:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=productdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  angular:
    image: joseabad985/wildfly-angular-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - wildfly

volumes:
  postgres_data: