services:
  postgres:
    image: joseabad985/wildfly-angular-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  wildfly:
    image: joseabad985/wildfly-angular-backend:latest
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=productdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - backend-network
      - frontend-backend-network

  angular:
    image: joseabad985/wildfly-angular-frontend:latest
    ports:
      - "8081:80"
    depends_on:
      - wildfly
    networks:
      - frontend-backend-network

networks:
  backend-network:
    internal: true
  frontend-backend-network:


volumes:
  postgres_data: